M48
; DRILL file {KiCad 7.0.7} date Mon Nov 27 18:28:31 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-27T18:28:31+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
%
G90
G05
T1
X10.11Y6.43
X15.89Y6.43
T2
X3.9Y64.37
X3.9Y62.67
X22.0Y64.37
X22.0Y62.67
T3
X2.0Y3.97
X13.0Y63.97
X24.0Y3.97
T0
M30
